Unittest attributes
funkwerk/accessors pull request #14
Opened 2017-10-26 15:54 UTC by belka-ew

2017-11-06 17:44 UTC, linkrope requested changes
`attributes` is either a bitset or a string (of joined strings). When both are used together, the bitset is named `attrs` or `attributeMask`.

It's better to distinguish `attributes` and `attributesString` from the beginning.

2017-11-06 17:44 UTC, linkrope commented on src/accessors.d
> +        S[] foo1_;
`foo(s)`, `bar`, `baz` instead of `foo1`, `foo2`, `foo3`

2017-11-06 17:51 UTC, linkrope requested changes

2017-11-06 17:51 UTC, linkrope commented on src/accessors.d
> +            return format("%s final @property auto %s() %s{"
always (also in `unittest`) keep the body on one line:

    ~ "{ return [] ~ this.%s; }

2017-11-06 17:51 UTC, linkrope commented on src/accessors.d
> +private template inferAttributes(T, string M)
`inferAttributes!(..., "__postblit")` looks strange, if `...` is no `struct`.

2017-11-06 17:51 UTC, linkrope commented on src/accessors.d
> +                attrs &= functionAttributes!(T.__postblit);
It's always `__postblit`, no matter what `M` is?

2017-11-07 15:21 UTC, belka-ew commented on src/accessors.d
> +private template inferAttributes(T, string M)
It means actually the same for all types:
Check if `T` has a method `__postblit` (whether or not it is a struct), if yes, return its attributes, otherwise return default attributes.
It is similar how `std.traits.hasElaborateCopyConstructor/hasElaborateDestructor` work for all types, even though only structs can have elaborate constructors/destructors/assign.
I can't think of a better short name now, but I'm open for suggestions..

2017-12-13 09:31 UTC, linkrope approved these changes

2017-12-13 13:05 UTC, merged