Deprecate RefRead
funkwerk/accessors pull request #18
Opened 2017-12-14 12:23 UTC by FeepingCreature

It's pointless and silly.

2017-12-14 14:09 UTC, belka-ew requested changes

2017-12-14 14:09 UTC, belka-ew commented on src/accessors.d
> +                        ~ " makes a private field effectively public, defeating the point.\");";
Better to use ` for the outer string to avoid escaping.

2017-12-14 16:22 UTC, linkrope approved these changes

2017-12-18 10:16 UTC, belka-ew commented
Merged.

2017-12-18 10:16 UTC, closed without merging